config/routes.rb
Rails.application.routes.draw do

mount Blazer::Engine, at: "blazer"

  resources :roles
  resources :subjects
  # get 'admin/index'
  # get 'sessions/new'

  get 'sessions/create'
  get 'sessions/destroy'

  resources :users

  get 'admin' => 'admin#index'

  
    controller :sessions do
        get 'login' => :new
        post 'login' => :create
        delete 'logout' => :destroy
    end

    

    root 'admin#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord

    # belongs_to :user
    # belongs_to :users, class_name: 'users', foreign_key: 'userid'
    belongs_to :user, :foreign_key => 'userid'
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:index, :show]
  # GET /subjects
  # GET /subjects.json
  def index

    # @tt = ['slot 1', 'slot 2', 'slot 3'];
    # ttc = [:slot1 => 'val 1 for slot 1', :slot2 => 'val 2 for slot 2', :slot3 => 'val 3 for slot 3' ];

    @subjects = Subject.all
    data = {};

    # data = '';

    @subjects.each_with_index  do |p, k|
      data[k] = p.title
      # data += p.title + "<br>"
    end

    render plain: data
    # render :text => "OK"

    # render inline: "<% @subjects.each do |p| %><p><%= p.title %><p><% end %>"
    # render html:  data.html_safe #{}"<strong>Not Found #{data}</strong>".html_safe
    # render json: @subjects
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new

    @usr = User.find( session[:user_id] )

    if @usr.role == '2'
      @subject = Subject.new
    else
      redirect_to subjects_url, notice: 'Only tutor can create subjects'
    end
    
  end

  # GET /subjects/1/edit
  def edit
  end



  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    @subject.userid = session[:user_id]

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:userid, :title, :author, :language, :comments)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :subject_title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :subject_author %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language, id: :subject_language %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_field :comments, id: :subject_comments %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>
<% 
  @usrrole = nil;
  if( !session[:user_id].blank? )  
   @usr = User.find( session[:user_id] )
   @usrrole = @usr.role
  end
%>

<h1>Subjects</h1>

<table width="100%">
  <thead>
    <tr>
      <th>Created By</th>
      <th>Title</th>
      <th>Author</th>
      <th>Language</th>
      <th>Comments</th>
      
      <% if @usrrole == '2' %>
        <th colspan="3"></th>
      <% else %>
        <th></th>
      <% end %>

    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= User.find(subject.userid).name %></td>
        <td><%= subject.title %></td>
        <td><%= subject.author %></td>
        <td><%= subject.language %></td>
        <td><%= subject.comments %></td>
        <td><%= link_to 'Show', subject %></td>
        <% if @usrrole == '2' %>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if @usrrole == '2' %>
<%= link_to 'New Subject', new_subject_path %>
<% end %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<% 
  @usrrole = nil;
  if( !session[:user_id].blank? )  
   @usr = User.find( session[:user_id] )
   @usrrole = @usr.role
  end
%>

<p>
  <strong>Created By:</strong>

  <%#= User.find(@subject.userid).name %>
  <%= @subject.user.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @subject.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @subject.author %>
</p>

<p>
  <strong>Language:</strong>
  <%= @subject.language %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @subject.comments %>
</p>

<% if @usrrole == '2' %>
<%= link_to 'Edit', edit_subject_path(@subject) %> |
<% end %>
<%= link_to 'Back', subjects_path %>