config/routes.rb
Rails.application.routes.draw do

mount Blazer::Engine, at: "blazer"

  resources :roles
  resources :subjects
  # get 'admin/index'
  # get 'sessions/new'

  get 'sessions/create'
  get 'sessions/destroy'

  resources :users

  get 'admin' => 'admin#index'

  
    controller :sessions do
        get 'login' => :new
        post 'login' => :create
        delete 'logout' => :destroy
    end

    

    root 'admin#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default ">
    <!-- navbar-fixed-top -->

      <div class="container">
        
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">First Project</a>
        </div>

        <div id="navbar" class="collapse navbar-collapse">
          
          <ul class="nav navbar-nav">

            <li><%= link_to "Home", admin_path %> </li>
              <li><%= link_to "Subjects", subjects_path %> </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">

            <% if session[:user_id] != nil %>
                
                <li><%= link_to "View Profile", user_path(session[:user_id]) %></li>
                <li><%= link_to "Edit Profile", edit_user_path(session[:user_id]) %></li>

                <li><%= link_to "Log out", sessions_destroy_path %> </li>

            <% else %>
                <li><%= link_to "Log in", login_url %> </li>
                <li><%= link_to "Signup", new_user_path %> </li>
            <% end %>

          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>


<div class="container">
    <%= yield %>
</div>


  </body>
</html>